# Base configs
baseurl: "https://emil83041.github.io/photography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Emil"
subtitle: ""
author: "Emil K"
header:
 title: "Photography"
 subtitle: "by Emil K"
footer:
 name: "Emil K"
 bio: ""
 github: ""
web_design: ""
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
